[package]
name = "nft-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-program = "1.18.18"
spl-token = { version = "4.0", features = ["no-entrypoint"] }
borsh = "0.9"